# Generated by Django 4.0 on 2024-02-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_barberprofile_is_staff_customerprofile_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberprofile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='is_superuser',
        ),
    ]
