# Generated by Django 4.0 on 2024-03-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_barberprofile_is_working_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberprofile',
            name='is_working',
        ),
    ]
