# Generated by Django 4.0 on 2024-03-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_barberprofile_is_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='reservation_system',
            field=models.BooleanField(default=False),
        ),
    ]
