# Generated by Django 4.0 on 2024-02-06 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days', models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')])),
                ('workstart', models.TimeField()),
                ('workfinish', models.TimeField()),
                ('reststart', models.TimeField()),
                ('restfinish', models.TimeField()),
                ('duration', models.IntegerField(choices=[(15, '15 minute'), (30, '30 minute'), (45, '45 minute'), (60, '60 minute')])),
                ('number_timeslots', models.IntegerField(blank=True, null=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.barberprofile')),
            ],
            options={
                'unique_together': {('barber', 'Days')},
            },
        ),
        migrations.CreateModel(
            name='ExcludedDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.barberprofile')),
            ],
            options={
                'unique_together': {('date', 'barber')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(choices=[(datetime.date(2024, 2, 6), '2024-02-06 | (Tuesday)'), (datetime.date(2024, 2, 7), '2024-02-07 | (Wednesday)'), (datetime.date(2024, 2, 8), '2024-02-08 | (Thursday)'), (datetime.date(2024, 2, 9), '2024-02-09 | (Friday)'), (datetime.date(2024, 2, 10), '2024-02-10 | (Saturday)'), (datetime.date(2024, 2, 11), '2024-02-11 | (Sunday)'), (datetime.date(2024, 2, 12), '2024-02-12 | (Monday)'), (datetime.date(2024, 2, 13), '2024-02-13 | (Tuesday)'), (datetime.date(2024, 2, 14), '2024-02-14 | (Wednesday)'), (datetime.date(2024, 2, 15), '2024-02-15 | (Thursday)'), (datetime.date(2024, 2, 16), '2024-02-16 | (Friday)'), (datetime.date(2024, 2, 17), '2024-02-17 | (Saturday)'), (datetime.date(2024, 2, 18), '2024-02-18 | (Sunday)'), (datetime.date(2024, 2, 19), '2024-02-19 | (Monday)'), (datetime.date(2024, 2, 20), '2024-02-20 | (Tuesday)'), (datetime.date(2024, 2, 21), '2024-02-21 | (Wednesday)'), (datetime.date(2024, 2, 22), '2024-02-22 | (Thursday)'), (datetime.date(2024, 2, 23), '2024-02-23 | (Friday)'), (datetime.date(2024, 2, 24), '2024-02-24 | (Saturday)'), (datetime.date(2024, 2, 25), '2024-02-25 | (Sunday)'), (datetime.date(2024, 2, 26), '2024-02-26 | (Monday)')])),
                ('time', models.TimeField()),
                ('status', models.BooleanField(default=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.barberprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile')),
            ],
            options={
                'unique_together': {('barber', 'date', 'time')},
            },
        ),
    ]
