# Generated by Django 4.0 on 2023-12-05 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days', models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')])),
                ('workstart', models.TimeField()),
                ('workfinish', models.TimeField()),
                ('reststart', models.TimeField()),
                ('restfinish', models.TimeField()),
                ('duration', models.IntegerField(choices=[(15, '15 minute'), (30, '30 minute'), (45, '45 minute'), (60, '60 minute')])),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.barberprofile')),
            ],
            options={
                'unique_together': {('barber', 'Days')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(choices=[(datetime.date(2023, 12, 5), '2023-12-05 | (Tuesday)'), (datetime.date(2023, 12, 6), '2023-12-06 | (Wednesday)'), (datetime.date(2023, 12, 7), '2023-12-07 | (Thursday)'), (datetime.date(2023, 12, 8), '2023-12-08 | (Friday)'), (datetime.date(2023, 12, 9), '2023-12-09 | (Saturday)'), (datetime.date(2023, 12, 10), '2023-12-10 | (Sunday)'), (datetime.date(2023, 12, 11), '2023-12-11 | (Monday)'), (datetime.date(2023, 12, 12), '2023-12-12 | (Tuesday)'), (datetime.date(2023, 12, 13), '2023-12-13 | (Wednesday)'), (datetime.date(2023, 12, 14), '2023-12-14 | (Thursday)'), (datetime.date(2023, 12, 15), '2023-12-15 | (Friday)'), (datetime.date(2023, 12, 16), '2023-12-16 | (Saturday)'), (datetime.date(2023, 12, 17), '2023-12-17 | (Sunday)'), (datetime.date(2023, 12, 18), '2023-12-18 | (Monday)'), (datetime.date(2023, 12, 19), '2023-12-19 | (Tuesday)'), (datetime.date(2023, 12, 20), '2023-12-20 | (Wednesday)'), (datetime.date(2023, 12, 21), '2023-12-21 | (Thursday)'), (datetime.date(2023, 12, 22), '2023-12-22 | (Friday)'), (datetime.date(2023, 12, 23), '2023-12-23 | (Saturday)'), (datetime.date(2023, 12, 24), '2023-12-24 | (Sunday)'), (datetime.date(2023, 12, 25), '2023-12-25 | (Monday)')])),
                ('time', models.TimeField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.barberprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile')),
            ],
            options={
                'unique_together': {('barber', 'date', 'time')},
            },
        ),
    ]
