# Generated by Django 4.0 on 2024-02-28 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(choices=[(datetime.date(2024, 2, 29), '2024-02-29 | (Thursday)'), (datetime.date(2024, 3, 1), '2024-03-01 | (Friday)'), (datetime.date(2024, 3, 2), '2024-03-02 | (Saturday)'), (datetime.date(2024, 3, 3), '2024-03-03 | (Sunday)'), (datetime.date(2024, 3, 4), '2024-03-04 | (Monday)'), (datetime.date(2024, 3, 5), '2024-03-05 | (Tuesday)'), (datetime.date(2024, 3, 6), '2024-03-06 | (Wednesday)'), (datetime.date(2024, 3, 7), '2024-03-07 | (Thursday)'), (datetime.date(2024, 3, 8), '2024-03-08 | (Friday)'), (datetime.date(2024, 3, 9), '2024-03-09 | (Saturday)'), (datetime.date(2024, 3, 10), '2024-03-10 | (Sunday)'), (datetime.date(2024, 3, 11), '2024-03-11 | (Monday)'), (datetime.date(2024, 3, 12), '2024-03-12 | (Tuesday)'), (datetime.date(2024, 3, 13), '2024-03-13 | (Wednesday)'), (datetime.date(2024, 3, 14), '2024-03-14 | (Thursday)'), (datetime.date(2024, 3, 15), '2024-03-15 | (Friday)'), (datetime.date(2024, 3, 16), '2024-03-16 | (Saturday)'), (datetime.date(2024, 3, 17), '2024-03-17 | (Sunday)'), (datetime.date(2024, 3, 18), '2024-03-18 | (Monday)'), (datetime.date(2024, 3, 19), '2024-03-19 | (Tuesday)'), (datetime.date(2024, 3, 20), '2024-03-20 | (Wednesday)')]),
        ),
    ]
