# Generated by Django 4.0 on 2023-12-09 21:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('booking', '0002_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(choices=[(datetime.date(2023, 12, 10), '2023-12-10 | (Sunday)'), (datetime.date(2023, 12, 11), '2023-12-11 | (Monday)'), (datetime.date(2023, 12, 12), '2023-12-12 | (Tuesday)'), (datetime.date(2023, 12, 13), '2023-12-13 | (Wednesday)'), (datetime.date(2023, 12, 14), '2023-12-14 | (Thursday)'), (datetime.date(2023, 12, 15), '2023-12-15 | (Friday)'), (datetime.date(2023, 12, 16), '2023-12-16 | (Saturday)'), (datetime.date(2023, 12, 17), '2023-12-17 | (Sunday)'), (datetime.date(2023, 12, 18), '2023-12-18 | (Monday)'), (datetime.date(2023, 12, 19), '2023-12-19 | (Tuesday)'), (datetime.date(2023, 12, 20), '2023-12-20 | (Wednesday)'), (datetime.date(2023, 12, 21), '2023-12-21 | (Thursday)'), (datetime.date(2023, 12, 22), '2023-12-22 | (Friday)'), (datetime.date(2023, 12, 23), '2023-12-23 | (Saturday)'), (datetime.date(2023, 12, 24), '2023-12-24 | (Sunday)'), (datetime.date(2023, 12, 25), '2023-12-25 | (Monday)'), (datetime.date(2023, 12, 26), '2023-12-26 | (Tuesday)'), (datetime.date(2023, 12, 27), '2023-12-27 | (Wednesday)'), (datetime.date(2023, 12, 28), '2023-12-28 | (Thursday)'), (datetime.date(2023, 12, 29), '2023-12-29 | (Friday)'), (datetime.date(2023, 12, 30), '2023-12-30 | (Saturday)')]),
        ),
        migrations.CreateModel(
            name='ExcludedDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.barberprofile')),
            ],
            options={
                'unique_together': {('date', 'barber')},
            },
        ),
    ]
