# Generated by Django 4.0 on 2024-03-11 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(choices=[(datetime.date(2024, 3, 11), '2024-03-11 | (Monday)'), (datetime.date(2024, 3, 12), '2024-03-12 | (Tuesday)'), (datetime.date(2024, 3, 13), '2024-03-13 | (Wednesday)'), (datetime.date(2024, 3, 14), '2024-03-14 | (Thursday)'), (datetime.date(2024, 3, 15), '2024-03-15 | (Friday)'), (datetime.date(2024, 3, 16), '2024-03-16 | (Saturday)'), (datetime.date(2024, 3, 17), '2024-03-17 | (Sunday)'), (datetime.date(2024, 3, 18), '2024-03-18 | (Monday)'), (datetime.date(2024, 3, 19), '2024-03-19 | (Tuesday)'), (datetime.date(2024, 3, 20), '2024-03-20 | (Wednesday)'), (datetime.date(2024, 3, 21), '2024-03-21 | (Thursday)'), (datetime.date(2024, 3, 22), '2024-03-22 | (Friday)'), (datetime.date(2024, 3, 23), '2024-03-23 | (Saturday)'), (datetime.date(2024, 3, 24), '2024-03-24 | (Sunday)'), (datetime.date(2024, 3, 25), '2024-03-25 | (Monday)'), (datetime.date(2024, 3, 26), '2024-03-26 | (Tuesday)'), (datetime.date(2024, 3, 27), '2024-03-27 | (Wednesday)'), (datetime.date(2024, 3, 28), '2024-03-28 | (Thursday)'), (datetime.date(2024, 3, 29), '2024-03-29 | (Friday)'), (datetime.date(2024, 3, 30), '2024-03-30 | (Saturday)'), (datetime.date(2024, 3, 31), '2024-03-31 | (Sunday)')]),
        ),
    ]
