# Generated by Django 4.0 on 2024-01-02 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_date_excludeddates'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerange',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(choices=[(datetime.date(2024, 1, 2), '2024-01-02 | (Tuesday)'), (datetime.date(2024, 1, 3), '2024-01-03 | (Wednesday)'), (datetime.date(2024, 1, 4), '2024-01-04 | (Thursday)'), (datetime.date(2024, 1, 5), '2024-01-05 | (Friday)'), (datetime.date(2024, 1, 6), '2024-01-06 | (Saturday)'), (datetime.date(2024, 1, 7), '2024-01-07 | (Sunday)'), (datetime.date(2024, 1, 8), '2024-01-08 | (Monday)'), (datetime.date(2024, 1, 9), '2024-01-09 | (Tuesday)'), (datetime.date(2024, 1, 10), '2024-01-10 | (Wednesday)'), (datetime.date(2024, 1, 11), '2024-01-11 | (Thursday)'), (datetime.date(2024, 1, 12), '2024-01-12 | (Friday)'), (datetime.date(2024, 1, 13), '2024-01-13 | (Saturday)'), (datetime.date(2024, 1, 14), '2024-01-14 | (Sunday)'), (datetime.date(2024, 1, 15), '2024-01-15 | (Monday)'), (datetime.date(2024, 1, 16), '2024-01-16 | (Tuesday)'), (datetime.date(2024, 1, 17), '2024-01-17 | (Wednesday)'), (datetime.date(2024, 1, 18), '2024-01-18 | (Thursday)'), (datetime.date(2024, 1, 19), '2024-01-19 | (Friday)'), (datetime.date(2024, 1, 20), '2024-01-20 | (Saturday)'), (datetime.date(2024, 1, 21), '2024-01-21 | (Sunday)'), (datetime.date(2024, 1, 22), '2024-01-22 | (Monday)')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
