# Generated by Django 4.0 on 2024-01-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_timerange_count_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timerange',
            old_name='count',
            new_name='number_timeslots',
        ),
    ]
