# Generated by Django 4.0 on 2024-03-14 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(choices=[(datetime.date(2024, 3, 14), '2024-03-14 | (Thursday)'), (datetime.date(2024, 3, 15), '2024-03-15 | (Friday)'), (datetime.date(2024, 3, 16), '2024-03-16 | (Saturday)'), (datetime.date(2024, 3, 17), '2024-03-17 | (Sunday)'), (datetime.date(2024, 3, 18), '2024-03-18 | (Monday)'), (datetime.date(2024, 3, 19), '2024-03-19 | (Tuesday)'), (datetime.date(2024, 3, 20), '2024-03-20 | (Wednesday)'), (datetime.date(2024, 3, 21), '2024-03-21 | (Thursday)'), (datetime.date(2024, 3, 22), '2024-03-22 | (Friday)'), (datetime.date(2024, 3, 23), '2024-03-23 | (Saturday)'), (datetime.date(2024, 3, 24), '2024-03-24 | (Sunday)'), (datetime.date(2024, 3, 25), '2024-03-25 | (Monday)'), (datetime.date(2024, 3, 26), '2024-03-26 | (Tuesday)'), (datetime.date(2024, 3, 27), '2024-03-27 | (Wednesday)'), (datetime.date(2024, 3, 28), '2024-03-28 | (Thursday)'), (datetime.date(2024, 3, 29), '2024-03-29 | (Friday)'), (datetime.date(2024, 3, 30), '2024-03-30 | (Saturday)'), (datetime.date(2024, 3, 31), '2024-03-31 | (Sunday)'), (datetime.date(2024, 4, 1), '2024-04-01 | (Monday)'), (datetime.date(2024, 4, 2), '2024-04-02 | (Tuesday)'), (datetime.date(2024, 4, 3), '2024-04-03 | (Wednesday)')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('pending', 'Pending')], default='confirmed', max_length=20),
        ),
    ]
